-- Track who voided a financial record, alongside when.
--
-- Generated by diffing drizzle/schema.ts against the previous committed
-- schema, then made re-runnable to match this repo's convention (see the
-- 0002 migration header): this repo's migrations are applied by hand and
-- may be retried. Additive only: no existing column is altered or dropped.

ALTER TABLE "offerings" ADD COLUMN IF NOT EXISTS "voidedBy" integer;--> statement-breakpoint
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "voidedAt" timestamp;--> statement-breakpoint
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "voidedBy" integer;
